In [ ]:
print('Pytorch')

Pytorch


In [1]:
!nvidia-smi

Sat Sep 21 07:06:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(pd.__version__)
print(np.__version__)

2.4.1+cu121
2.1.4
1.26.4


Introduction to tensors


creating tensors

In [9]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim # has no dimensions

0

In [12]:
scalar.item() # returns tensor as python int

7

In [13]:
# vector -> magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [20]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [23]:
MATRIX.ndim

2

In [25]:
MATRIX[0]

tensor([7, 8])

In [24]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [27]:
TENSOR.ndim

3

In [28]:
TENSOR.shape

torch.Size([1, 3, 3])

In [29]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
TENSOR[0][0][2]

tensor(3)

In [35]:
# Radnom tensors
# why random tensors :
# beacause the way neural networks learn is that they start with tensors full of random numbers and then
# adjust those random numbers to better represent the data.

# start with random num -> look at data -> update random numbers -> look at data -> update random numbers.


In [42]:
# creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7542, 0.9630, 0.3714, 0.5728],
        [0.7647, 0.4650, 0.7781, 0.8908],
        [0.6236, 0.0736, 0.7548, 0.0966]])

In [43]:
random_tensor.ndim

2

In [44]:
random_tensor.shape

torch.Size([3, 4])

In [48]:
# create a random tensor with similiar shape to an image tensor

random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width ,color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

ZEROS AND ONES

In [51]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
onesb

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [54]:
ones.dtype

torch.float32

In [55]:
random_tensor.dtype

torch.float32

creating range of tensors and tensorlike

In [60]:
# torch.range() is deprecated using torch.arange()
one_to_ten = torch.arange(start=1, end=11, step = 1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
# creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [67]:
# flaot32
float32_tensor = torch.tensor([3., 6., 9.],
                              dtype=None,  # what datatype tensor (f18, f32)
                              device="cpu", #
                              requires_grad = False)
float32_tensor

tensor([3., 6., 9.])

In [68]:
float32_tensor.dtype

torch.float32

In [69]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [73]:
 float32_tensor + float16_tensor

tensor([ 6., 12., 18.])