In [ ]:
print('Pytorch')

Pytorch


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(pd.__version__)
print(np.__version__)

2.4.1+cu121
2.1.4
1.26.4


Introduction to tensors


creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # has no dimensions

0

In [ ]:
scalar.item() # returns tensor as python int

7

In [ ]:
# vector -> magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][0][2]

tensor(3)

In [ ]:
# Radnom tensors
# why random tensors :
# beacause the way neural networks learn is that they start with tensors full of random numbers and then
# adjust those random numbers to better represent the data.

# start with random num -> look at data -> update random numbers -> look at data -> update random numbers.


In [ ]:
# creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7999, 0.1424, 0.9289, 0.0416],
        [0.7323, 0.1045, 0.0084, 0.1675],
        [0.4294, 0.1580, 0.3261, 0.9408]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# create a random tensor with similiar shape to an image tensor

random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width ,color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

ZEROS AND ONES

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
onesb

NameError: name 'onesb' is not defined

In [ ]:
ones.dtype

In [ ]:
random_tensor.dtype

creating range of tensors and tensorlike

In [ ]:
# torch.range() is deprecated using torch.arange()
one_to_ten = torch.arange(start=1, end=11, step = 1)
one_to_ten


In [ ]:
# creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

Tensor Datatypes

In [ ]:
# flaot32
float32_tensor = torch.tensor([3., 6., 9.],
                              dtype=None,  # what datatype tensor (f18, f32)
                              device="cpu", #
                              requires_grad = False)
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Getting information from tensor

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3732, 0.3200, 0.4766, 0.3400],
        [0.1122, 0.1419, 0.0112, 0.8708],
        [0.1310, 0.1304, 0.9836, 0.5558]])

In [ ]:
print(some_tensor)
print(f"DataType of tensor : {some_tensor.dtype}\n")
print(f"Shape of tensor : {some_tensor.shape}\n")
print(f"Size of tensor : {some_tensor.size()}\n")
print(f"Device of tensor : {some_tensor.device}\n")

Manipulating Tensors (Tensor Operation)  
It includes  
- Addition  
- Subtraction  
- Multiplication (element-wise)  
- Division  
- Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor, 10) # built in pytorch func

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

MATRIX Multiplication

two ways to perform multiplication in neural networks and deep learning

1. Element wise
2. Matrix mulitplication (dot product)  

There are two main rules to follow while matrix multiplying :  

1. Inner dimensions must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work  
2. The resulting matrix has shape of outer matrix
* `(2,3) @ (3,2)` will have shape of `(2,2)`


In [ ]:
# Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
tensor @ tensor

tensor(14)

One of them most common errors in deep learnig : shape errors

Tensor aggregation (min, max, avg...)

In [2]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
# min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [4]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [6]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [8]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

 finding positional min and max

In [10]:
# find the position in tensor that has minimum value with argmin
# returns index where minimum value is
x.argmin()

tensor(0)

In [11]:
x.argmax()

tensor(9)

Reshaping , viewing, and stacking tensors  
squeezing and unsqueezing  

* reshaping - reshapes an input tensor to a defined shape,
* View - Return a view of an input tensor of certain shape but keeps the same memory as orginal tensor
* Stacking - combine multiple tensors on top of each other (hstack / vstack)
* Squeeze - removes all `1` dimensions from a tensors
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [1]:
import torch

In [16]:
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [18]:
# adding an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped.shape, x_reshaped

(torch.Size([1, 9]), tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [19]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [22]:
# changing z changes x becauase the view of tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [25]:
# stack tensors on top on each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [46]:
# unsqueeze  - byself
x_unsqueezed = torch.unsqueeze(x, 0)
x, x.shape, '\n' , x_unsqueezed  , x_unsqueezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 '\n',
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [48]:
# squeeze - by self
x_squeezed = torch.squeeze(x, 0)
x, x.shape, '\n' , x_squeezed  , x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 '\n',
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [51]:
# torch.squeeze() - removes all single dimensions from target tensor
x = torch.zeros(1,2,1,2,1,2)
y = torch.squeeze(x)
y.shape, y.size()
y = torch.squeeze(x, 0)
y.shape
y = torch.squeeze(x, 4)
y.shape

In [62]:
# squeeze
print(x_reshaped.shape)
x_reshaped.squeeze().shape

torch.Size([1, 9])


torch.Size([9])

In [67]:
# torch.unsqueeze() - adds a single dim to a target tensor at specific dim
print(f'previous target , {x_squeezed}')
print(f'previous shape , {x_squeezed.shape}')

# adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed.shape, x_unsqueezed



previous target , tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape , torch.Size([9])


(torch.Size([9, 1]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [69]:
# torch.permute() - rearranges the dimensiosns of a target tensor in a specified order
# returns a view
x_original = torch.rand(size=(224,224, 3)) # (h, w, cChanels)

# permute to rearange the axis (dim)
x_permuted = x_original.permute(2,0,1)
x_original.shape , x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [71]:
x_original[0,0,0] = 1.22222
x_original[0,0,0]

tensor(1.2222)

In [72]:
# changed as permute() returns views of orignal tensor and view shares the same memory
x_permuted[0,0,0]

tensor(1.2222)

Indexing (selecting data from tensors)  
  
Indexing in pytorch is similiar to indexing in NumPy

In [75]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [76]:
# let's index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [87]:
# lets index on middle bracket dim=1
x[0,0] # same as x[0][0]

tensor([1, 2, 3])

In [88]:
# let's index on most inner bracket last dim
x[0][2][2]

tensor(9)

In [98]:
x[:,0]

tensor([[1, 2, 3]])

In [97]:
# get all values of 0 and 1 dim but only index 1 of 2 dim
x[:,:,1]

tensor([[2, 5, 8]])

In [100]:
# Get all values of 0 dimension but only the 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [101]:
# get index 0 of 0th and 1st dim and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [102]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [104]:
# index on x to return 9
print(x[0,2,2])

# index on x to return 3,6,9
print(x[0,:,2])

tensor(9)
tensor([3, 6, 9])


Pytorch tensors and NumPy  
NumPy is a popular scientific Python numerical libraray,   
becuase of this , pytorch has functionality to interact with it.  

* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> NumPy -> `torch.Tensor,numpy()`  

In [110]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)  # pytorch defaults datatype to float64 unless specified
array, array.dtype, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [111]:
  # Change the value of array , what will this do to `tensor`?
  array = array + 1
  array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [112]:
# tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Pytorch Reproducability (taking random out of randomness)  
In short how a neural network learns :

`start with random numbers -> tensor operation -> update random to try and make them better representation of data -> again -> again ...`  

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed** .

essentially what the random seed does is "flavour" the randomness.

In [114]:
torch.rand(3,3)

tensor([[0.6742, 0.6620, 0.2760],
        [0.9901, 0.2242, 0.3772],
        [0.6930, 0.7555, 0.2649]])

In [116]:
random_tensor_A  = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0784, 0.1354, 0.4483, 0.1430],
        [0.8446, 0.4511, 0.6186, 0.7808],
        [0.1317, 0.4309, 0.8274, 0.1757]])
tensor([[0.5481, 0.5061, 0.2342, 0.9782],
        [0.4237, 0.8376, 0.7312, 0.2815],
        [0.6591, 0.5295, 0.5402, 0.8249]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [119]:
# let's make some random but reproducible tensors
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors and Pytorch obj on GPU (and making faster computations)

GPUs = faster computation on numbers , thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes.


In [1]:
!nvidia-smi

Tue Sep 24 09:01:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# checking gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [7]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
# count no of devices
torch.cuda.device_count()

1

In [5]:
# putting tensors and models on the GPU

tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [9]:
# Moving back to CPU
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
# to fix this issue we have to first set it to CPU
tensor_back_to_cpu = tensor_on_gpu.cpu()
tensor_back_to_cpu

tensor([1, 2, 3])

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')