In [ ]:
print('Pytorch')

Pytorch


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(pd.__version__)
print(np.__version__)

2.4.1+cu121
2.1.4
1.26.4


Introduction to tensors


creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # has no dimensions

0

In [ ]:
scalar.item() # returns tensor as python int

7

In [ ]:
# vector -> magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][0][2]

tensor(3)

In [ ]:
# Radnom tensors
# why random tensors :
# beacause the way neural networks learn is that they start with tensors full of random numbers and then
# adjust those random numbers to better represent the data.

# start with random num -> look at data -> update random numbers -> look at data -> update random numbers.


In [ ]:
# creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7999, 0.1424, 0.9289, 0.0416],
        [0.7323, 0.1045, 0.0084, 0.1675],
        [0.4294, 0.1580, 0.3261, 0.9408]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# create a random tensor with similiar shape to an image tensor

random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width ,color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

ZEROS AND ONES

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
onesb

NameError: name 'onesb' is not defined

In [ ]:
ones.dtype

In [ ]:
random_tensor.dtype

creating range of tensors and tensorlike

In [ ]:
# torch.range() is deprecated using torch.arange()
one_to_ten = torch.arange(start=1, end=11, step = 1)
one_to_ten


In [ ]:
# creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

Tensor Datatypes

In [ ]:
# flaot32
float32_tensor = torch.tensor([3., 6., 9.],
                              dtype=None,  # what datatype tensor (f18, f32)
                              device="cpu", #
                              requires_grad = False)
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Getting information from tensor

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3732, 0.3200, 0.4766, 0.3400],
        [0.1122, 0.1419, 0.0112, 0.8708],
        [0.1310, 0.1304, 0.9836, 0.5558]])

In [ ]:
print(some_tensor)
print(f"DataType of tensor : {some_tensor.dtype}\n")
print(f"Shape of tensor : {some_tensor.shape}\n")
print(f"Size of tensor : {some_tensor.size()}\n")
print(f"Device of tensor : {some_tensor.device}\n")

Manipulating Tensors (Tensor Operation)  
It includes  
- Addition  
- Subtraction  
- Multiplication (element-wise)  
- Division  
- Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor, 10) # built in pytorch func

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

MATRIX Multiplication

two ways to perform multiplication in neural networks and deep learning

1. Element wise
2. Matrix mulitplication (dot product)  

There are two main rules to follow while matrix multiplying :  

1. Inner dimensions must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work  
2. The resulting matrix has shape of outer matrix
* `(2,3) @ (3,2)` will have shape of `(2,2)`


In [ ]:
# Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
tensor @ tensor

tensor(14)

One of them most common errors in deep learnig : shape errors

Tensor aggregation (min, max, avg...)

In [2]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
# min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [4]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [6]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [8]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

 finding positional min and max

In [10]:
# find the position in tensor that has minimum value with argmin
# returns index where minimum value is
x.argmin()

tensor(0)

In [11]:
x.argmax()

tensor(9)

Reshaping , viewing, and stacking tensors  
squeezing and unsqueezing  

* reshaping - reshapes an input tensor to a defined shape,
* View - Return a view of an input tensor of certain shape but keeps the same memory as orginal tensor
* Stacking - combine multiple tensors on top of each other (hstack / vstack)
* Squeeze - removes all `1` dimensions from a tensors
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [1]:
import torch

In [16]:
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [18]:
# adding an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped.shape, x_reshaped

(torch.Size([1, 9]), tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [19]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [22]:
# changing z changes x becauase the view of tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [25]:
# stack tensors on top on each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [46]:
# unsqueeze  - byself
x_unsqueezed = torch.unsqueeze(x, 0)
x, x.shape, '\n' , x_unsqueezed  , x_unsqueezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 '\n',
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [48]:
# squeeze - by self
x_squeezed = torch.squeeze(x, 0)
x, x.shape, '\n' , x_squeezed  , x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 '\n',
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [51]:
# torch.squeeze() - removes all single dimensions from target tensor
x = torch.zeros(1,2,1,2,1,2)
y = torch.squeeze(x)
y.shape, y.size()
y = torch.squeeze(x, 0)
y.shape
y = torch.squeeze(x, 4)
y.shape

In [62]:
# squeeze
print(x_reshaped.shape)
x_reshaped.squeeze().shape

torch.Size([1, 9])


torch.Size([9])

In [67]:
# torch.unsqueeze() - adds a single dim to a target tensor at specific dim
print(f'previous target , {x_squeezed}')
print(f'previous shape , {x_squeezed.shape}')

# adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed.shape, x_unsqueezed



previous target , tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape , torch.Size([9])


(torch.Size([9, 1]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [69]:
# torch.permute() - rearranges the dimensiosns of a target tensor in a specified order
# returns a view
x_original = torch.rand(size=(224,224, 3)) # (h, w, cChanels)

# permute to rearange the axis (dim)
x_permuted = x_original.permute(2,0,1)
x_original.shape , x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [71]:
x_original[0,0,0] = 1.22222
x_original[0,0,0]

tensor(1.2222)

In [72]:
# changed as permute() returns views of orignal tensor and view shares the same memory
x_permuted[0,0,0]

tensor(1.2222)